name: Build & Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build
          
      - name: Deploy
        uses: LubricantJam/SFTP-Deploy-Action@v2.1
        with: 
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_NAME }}
          ssh_password: ${{ secrets.SERVER_PASSWORD }}
          local_path: './build/*'      # default is .
          remote_path: '/build/'    # default is .
          ssh_command: exit
          compress: true
          
